Repository KFE-E2E-SAJO/BIDER, pull requests merged in 2025-06, with the labels that each got.

#8 [⚙️ chore] global.css 수정
  packages/ui/src/global.css
Labels: chore

#9 [✨ feat] 공통 컴포넌트 구현 (Tooltip)
  apps/storybook/stories/Tooltip.stories.tsx
  packages/ui/src/components/Tooltip/Tooltip.tsx
Labels: feat

#11 [✨ feat] 공통컴포넌트 구현(Button, Checkbox)
  apps/storybook/stories/Button.stories.tsx
  apps/storybook/stories/Checkbox.stories.tsx
  packages/ui/package.json
  packages/ui/src/components/Button/Button.tsx
  packages/ui/src/components/Checkbox/Base.tsx
  packages/ui/src/components/Checkbox/Checkbox.tsx
  packages/ui/src/components/Label/Label.tsx
  packages/ui/src/global.css
  packages/ui/src/lib/utils.ts
  pnpm-lock.yaml
Labels: feat

#14 [✨ feat] 공통 컴포넌트 구현(Input, Modal)
  apps/storybook/stories/Dialog.stories.tsx
  apps/storybook/stories/Input.stories.tsx
  apps/storybook/stories/Modal.stories.tsx
  packages/ui/package.json
  packages/ui/src/components/DIalog/dialog.tsx
  packages/ui/src/components/Input/Input.tsx
  packages/ui/src/components/Input/textInput.tsx
  packages/ui/src/components/Modal/Modal.tsx
  pnpm-lock.yaml
Labels: feat

#21 [🐞 hotfix] web패키지 Tailwind 버전 업그레이드
  apps/web/app/page.module.css
  apps/web/next.config.js
  apps/web/package.json
  apps/web/postcss.config.js
  apps/web/styles/global.css
  apps/web/tailwind.config.js
  apps/web/tailwind.config.ts
  packages/ui/src/global.css
  pnpm-lock.yaml
Labels: hotfix

#24 [✨ feat] supabase 연동 설정
  apps/web/app/layout.tsx
  apps/web/package.json
  apps/web/shared/lib/supabaseClient.ts
  packages/ui/src/global.css
  pnpm-lock.yaml
Labels: feat

#38 [🐞 hotfix] textarea height 변경 안되는 문제 수정 (#31)
  apps/storybook/stories/Toaster.stories.tsx
  apps/web/app/page.tsx
  packages/ui/package.json
  packages/ui/src/components/Textarea/Textarea.tsx
  packages/ui/src/components/Toast/Sonner.tsx
  packages/ui/src/components/Toast/Toast.tsx
  pnpm-lock.yaml
Labels: hotfix

#42 [✨ feat] 상품 등록 페이지, 기능 구현
  apps/web/.github/workflows/cron-auction.yml
  apps/web/app/api/cron/create-auction/route.ts
  apps/web/app/api/product/route.ts
  apps/web/app/product/registration/ImageUploadPreview.tsx
  apps/web/app/product/registration/page.tsx
  apps/web/package.json
  apps/web/styles/global.css
  packages/ui/src/global.css
  pnpm-lock.yaml
Labels: design, feat

#61 [✨ feat] 마이페이지 구현
  apps/web/app/(base)/layout.tsx
  apps/web/app/(base)/mypage/page.tsx
  apps/web/app/(header)/layout.tsx
  apps/web/app/(header)/mypage/edit/page.tsx
  apps/web/app/(header)/product/[shortId]/BottomBar.tsx
  apps/web/app/(header)/product/[shortId]/ProductImageSlider.tsx
  apps/web/app/(header)/product/[shortId]/page.tsx
  apps/web/app/(header)/product/registration/ImageUploadPreview.tsx
  apps/web/app/(header)/product/registration/page.tsx
  apps/web/app/(plane)/(location)/setLocation/page.tsx
  apps/web/app/api/mypage/route.ts
  apps/web/app/layout.tsx
  apps/web/features/myPage/edit/index.tsx
  apps/web/features/myPage/edit/model/setUserInfo.ts
  apps/web/features/myPage/edit/ui/ProfileInputList.tsx
  apps/web/features/myPage/edit/ui/ProfilePreview.tsx
  apps/web/features/myPage/index.tsx
  apps/web/features/myPage/lib/session.ts
  apps/web/features/myPage/ui/MyPageAuction.tsx
  apps/web/features/myPage/ui/MyPageAuctionCard.tsx
  apps/web/features/myPage/ui/MyPageMenuItem.tsx
  apps/web/features/myPage/ui/MyPageMenuList.tsx
  apps/web/features/myPage/ui/MypageProfileCard.tsx
  apps/web/shared/ui/badge/StatusBadge.tsx
  apps/web/shared/ui/button/BackBtn.tsx
  apps/web/widgets/footer/Footer.tsx
  apps/web/widgets/header/ui/HeaderItem.tsx
  packages/ui/src/components/Avatar/Avatar.tsx
  packages/ui/src/components/Button/Button.tsx
  packages/ui/src/components/Dialog/Dialog.tsx
  packages/ui/src/components/Icon/AvatarFallbakIcon.tsx
  packages/ui/src/global.css
Labels: design, feat
