Repository KFE-E2E-SAJO/BIDER, pull requests merged in 2025-07, with the labels that each got.

#76 [✨ feat] 검색페이지 화면 기능구현
  apps/web/app/(plane)/search/page.tsx
  apps/web/app/search/page.tsx
  apps/web/package.json
  pnpm-lock.yaml
Labels: feat

#87 [🐞 hotfix] zustand 설치 관련 경로 이동
  apps/web/features/login/LogInForm.tsx
  apps/web/shared/model/authStore.ts
  package.json
Labels: hotfix

#90 [✨ feat] 낙찰/유찰/패찰 기능 구현
  apps/web/.github/workflows/cron-resolve-auction.yml
  apps/web/app/api/cron/resolve-auction/route.ts
Labels: feat

#97 [🐞 hotfix] dialog 대소문자 구분
  apps/web/app/(header)/auction/[shortId]/BottomBar.tsx
  apps/web/features/mypage/edit/ui/ProfilePreview.tsx
  apps/web/shared/lib/ImageUploadPreview.tsx
  packages/ui/src/components/abcd/Abcd.tsx
Labels: hotfix

#99 [🐞 hotfix] dialog 대소문자 변경2 #98
  apps/web/app/(header)/auction/[shortId]/BottomBar.tsx
  apps/web/features/mypage/edit/ui/ProfilePreview.tsx
  apps/web/shared/lib/ImageUploadPreview.tsx
  packages/ui/src/components/Dialog/Dialog.tsx
Labels: hotfix

#91 [✨ feat] 나의 입찰내역/출품내역 페이지 구현
  apps/web/app/(header)/auction/[shortId]/BottomBar.tsx
  apps/web/app/(header)/auction/bids/page.tsx
  apps/web/app/(header)/auction/listings/page.tsx
  apps/web/features/Product/types/index.ts
  apps/web/features/Product/ui/ProductActionBtn.tsx
  apps/web/features/Product/ui/ProductBadge.tsx
  apps/web/features/Product/ui/ProductItem.tsx
  apps/web/features/Product/ui/ProductList.tsx
  apps/web/features/auction/bids/index.tsx
  apps/web/features/auction/bids/lib/util.ts
  apps/web/features/auction/bids/model/getBidList.ts
  apps/web/features/auction/bids/ui/BidList.tsx
  apps/web/features/auction/listings/index.tsx
  apps/web/features/auction/listings/lib/util.ts
  apps/web/features/auction/listings/model/getListingList.ts
  apps/web/features/auction/listings/ui/ListingList.tsx
  apps/web/features/auction/shared/ui/AuctionTaopTabs.tsx
  apps/web/features/mypage/edit/index.tsx
  apps/web/features/mypage/edit/ui/ProfilePreview.tsx
  apps/web/features/mypage/index.tsx
  apps/web/features/mypage/ui/MyPageAuction.tsx
  apps/web/shared/lib/ImageUploadPreview.tsx
  apps/web/shared/ui/badge/StatusBadge.tsx
  packages/ui/src/components/Dialog/Dialog.tsx
  packages/ui/src/components/Tabs/Tabs.tsx
Labels: design, feat

#107 [🐞 hotfix] ProductActionBtn 컴포넌트 경로 수정
  apps/web/app/api/product/route.ts
  apps/web/features/Product/ui/ProductItem.tsx
  apps/web/features/Product/ui/ProductList.tsx
Labels: hotfix

#120 [🐞 hotfix] 토큰별, 위치 설정별 splash 페이지 이동
  apps/web/app/splash/page.tsx
Labels: hotfix

#136 [🐞 hotfix] 상품 수정 시 이미지가 삭제되는 오류 수정
  apps/web/app/(header)/product/edit/[shortId]/page.tsx
  apps/web/app/api/product/edit/[shortId]/route.ts
Labels: hotfix

#138 [🐞 hotfix] 경매 상태 뱃지 수정, 입찰 횟수 미노출
  apps/web/features/mypage/ui/MypageProfileCard.tsx
  apps/web/features/product/ui/ProductBadge.tsx
  apps/web/features/product/ui/ProductItem.tsx
Labels: hotfix

#152 [✨ feat] 입찰 완료 페이지
  apps/web/app/(header)/bid/complete/page.tsx
  apps/web/app/api/auction/[shortId]/route.ts
  apps/web/entities/auction/model/types.ts
  apps/web/features/auction/bids/lib/utils.ts
  apps/web/features/auction/bids/model/bidStore.ts
  apps/web/features/auction/bids/model/useBidSubmit.ts
  apps/web/features/auction/bids/types/index.ts
  apps/web/features/auction/bids/ui/BidCompleteView.tsx
Labels: design, feat

#151 [♻️ refactor] 상품 리스트, 위치설정 코드 리팩토링
  apps/web/app/(base)/page.tsx
  apps/web/app/(header)/product/page.tsx
  apps/web/app/(plane)/search/page.tsx
  apps/web/app/api/product/route.ts
  apps/web/entities/auction/model/types.ts
  apps/web/entities/product/model/types.ts
  apps/web/features/auction/bids/model/getBidList.ts
  apps/web/features/auction/bids/model/useGetBidList.ts
  apps/web/features/auction/listings/model/getListingList.ts
  apps/web/features/auction/listings/model/useGetListingList.ts
  apps/web/features/category/types/index.ts
  apps/web/features/category/ui/Category.tsx
  apps/web/features/category/ui/GridCategory.tsx
  apps/web/features/category/ui/InlineCategory.tsx
  apps/web/features/location/api/getAddressFromLatLng.ts
  apps/web/features/location/api/getKoreanAddress.ts
  apps/web/features/location/api/updateLocation.ts
  apps/web/features/location/model/useLocationStore.ts
  apps/web/features/location/model/useUpdateLocation.ts
  apps/web/features/location/types/index.ts
  apps/web/features/location/ui/DotStepper.tsx
  apps/web/features/location/ui/GoggleMap.tsx
  apps/web/features/location/ui/LocationConfirm.tsx
  apps/web/features/location/ui/LocationIntro.tsx
  apps/web/features/location/ui/LocationSuccess.tsx
  apps/web/features/location/ui/LocationWrapper.tsx
  apps/web/features/product/api/getProductList.ts
  apps/web/features/product/model/useProductList.ts
  apps/web/features/product/model/useProductListErrorHandler.ts
  apps/web/features/product/types/index.ts
  apps/web/features/product/ui/LocationPin.tsx
  apps/web/features/product/ui/ProductItem.tsx
  apps/web/features/product/ui/ProductList.tsx
  apps/web/features/search/ui/ResultSection.tsx
Labels: refactor

#162 [✨ feat] 입찰현황판 구현
  apps/web/app/api/auction/[shortId]/route.ts
  apps/web/entities/auction/model/types.ts
  apps/web/entities/bidHistory/model/types.ts
  apps/web/features/auction/bids/ui/BidDialog.tsx
  apps/web/features/auction/detail/api/useBidHistoryRealtime.ts
  apps/web/features/auction/detail/types/index.ts
  apps/web/features/auction/detail/ui/AuctionDetailPage.tsx
  apps/web/features/auction/detail/ui/BiddingStatusBoard.tsx
  apps/web/shared/lib/supabaseClient.ts
  pnpm-lock.yaml
Labels: design, feat

#178 [🔧 fix] 출품 내역 금액 수정
  apps/web/features/auction/listings/model/getListingList.ts
Labels: fix

#176 [♻️ refactor] splash 로딩/초기 화면 분리
  apps/web/app/(plane)/splash/loading/page.tsx
  apps/web/app/(plane)/splash/model/useSplashTimer.ts
  apps/web/app/(plane)/splash/page.tsx
  apps/web/app/(plane)/splash/ui/splashStartButton.tsx
  apps/web/app/(plane)/splash/welcome/page.tsx
  apps/web/shared/lib/middleware/redirect.ts
Labels: refactor

#172 [♻️ refactor] 유효성 검사 로직 수정
  apps/web/app/(plane)/login/page.tsx
  apps/web/features/find-id/model/useFindId.ts
  apps/web/features/login/model/useLogin.ts
  apps/web/features/login/ui/LogInForm.tsx
  apps/web/shared/lib/validation/email.ts
Labels: refactor

#174 [♻️ refactor] 미등록자 비밀번호 찾기 실행 시 이메일 전송 이슈
  apps/web/features/find-id/model/useFindId.ts
Labels: refactor

#180 [🔧 fix] pnpm-lock 파일 수정
  pnpm-lock.yaml
Labels: fix

#182 [♻️ refactor] 미들웨어 인증 구현
  apps/web/app/api/auth/login/route.ts
  apps/web/app/api/auth/me/route.ts
  apps/web/features/login/model/useLogin.ts
  apps/web/shared/lib/middleware/redirect.ts
  apps/web/shared/model/authStore.ts
  apps/web/shared/model/useAuth.ts
Labels: refactor

#203 [🐞 hotfix] 회원가입 이메일 인증 리디렉션
  apps/web/shared/lib/auth.ts
Labels: hotfix

#200 [✨ design] css 수정
  apps/web/app/(base)/layout.tsx
  apps/web/app/(base)/page.tsx
  apps/web/app/(header)/auction/[shortId]/page.tsx
  apps/web/app/(header)/layout.tsx
  apps/web/app/(plane)/find-id/page.tsx
  apps/web/app/(plane)/login/page.tsx
  apps/web/app/(plane)/signup/page.tsx
  apps/web/app/(plane)/splash/welcome/page.tsx
  apps/web/features/auction/detail/ui/AuctionDetailPage.tsx
  apps/web/features/auction/detail/ui/BottomBar.tsx
  apps/web/features/category/ui/InlineCategory.tsx
  apps/web/features/find-id/lib/findAccountConfig.tsx
  apps/web/features/login/ui/LogInForm.tsx
  apps/web/features/product/ui/LocationPin.tsx
  apps/web/features/product/ui/ProductRegistrationForm.tsx
  apps/web/features/signup/SignUpForm.tsx
  apps/web/features/signup/ui/ConfirmPassword.tsx
  apps/web/features/signup/ui/EmailField.tsx
  apps/web/features/signup/ui/NicknameField.tsx
  apps/web/features/signup/ui/PasswordField.tsx
  apps/web/shared/lib/ImageUploadPreview.tsx
  apps/web/styles/global.css
  packages/ui/src/components/Input/Input.tsx
  packages/ui/src/global.css
Labels: design

#205 [🐞 hotfix] 비번찾기 이메일인증 리디렉션 재연결
  apps/web/app/(header)/product/page.tsx
  apps/web/app/(plane)/find-id/page.tsx
  apps/web/app/(plane)/login/page.tsx
  apps/web/app/(plane)/signup/page.tsx
  apps/web/features/find-id/model/useFindId.ts
  apps/web/features/login/ui/LogInForm.tsx
  apps/web/features/signup/SignUpForm.tsx
  apps/web/shared/lib/middleware/redirect.ts
Labels: hotfix

#241 [✨ feat] 경매 상품 관련 스케줄러 로직에 배포 URL 설정
  apps/web/.github/workflows/cron-auction.yml
  apps/web/.github/workflows/cron-resolve-auction.yml
  apps/web/app/api/cron/create-auction/route.ts
  apps/web/app/api/cron/resolve-auction/route.ts
Labels: feat

#246 [🐞 hotfix] 스케줄러 파일이 apps 하위에 있어서 스케줄러가 돌지 않는 이슈
  .github/workflows/cron-auction.yml
  .github/workflows/cron-resolve-auction.yml
Labels: hotfix

#260 [🔧 fix] 개발 중인 코드의 에러도 sentry 에러로 전송되는 이슈
  apps/web/instrumentation-client.ts
  apps/web/sentry.edge.config.ts
  apps/web/sentry.server.config.ts
Labels: fix

#275 [🔧 fix] 경매 대기 안내 추가, 내 경매 상태 링크 연결
  apps/web/app/(base)/layout.tsx
  apps/web/app/(header)/auction/bids/page.tsx
  apps/web/app/(header)/auction/listings/page.tsx
  apps/web/app/(header)/layout.tsx
  apps/web/app/(header)/product/page.tsx
  apps/web/features/auction/bids/index.tsx
  apps/web/features/auction/listings/index.tsx
  apps/web/features/auction/shared/types/index.ts
  apps/web/features/auction/shared/ui/UrlSyncTabs.tsx
  apps/web/features/mypage/types/index.ts
  apps/web/features/mypage/ui/MyPageAuction.tsx
  apps/web/features/mypage/ui/MyPageAuctionCard.tsx
  apps/web/features/product/ui/ProductRegistrationForm.tsx
  apps/web/widgets/nav/Nav.tsx
  packages/ui/src/components/Dialog/Dialog.tsx
Labels: fix

#288 [🐞 hotfix] 입찰현황판 관련 이슈
  apps/web/features/auction/detail/api/useBidHistoryRealtime.ts
  apps/web/features/auction/detail/types/index.ts
  apps/web/features/auction/detail/ui/AuctionDetailPage.tsx
  apps/web/features/auction/detail/ui/BiddingStatusBoard.tsx
Labels: hotfix

#294 [🐞 hotfix] 로그인/ 로그아웃 시 localstorage-> server session 저장 및 로그아웃 시 경로 설정
  apps/web/app/api/auth/login/route.ts
  apps/web/app/api/auth/logout/route.ts
  apps/web/app/api/auth/me/route.ts
  apps/web/features/login/model/useLogin.ts
  apps/web/shared/lib/middleware/redirect.ts
  apps/web/shared/model/useAuth.ts
  apps/web/widgets/footer/Footer.tsx
Labels: hotfix

#299 [🔧 fix] 내부 이슈 테스트 대비 수정
  apps/web/features/mypage/ui/MyPageMenuList.tsx
Labels: fix

#305 [⚙️ chore] RootLayout 수정
  apps/web/app/layout.tsx
  apps/web/widgets/nav/Nav.tsx
  packages/ui/src/global.css
Labels: chore

#310 [🐞 hotfix] 입찰 후 상세페이지 조회 시 직전 입찰이 반영되지 않은 화면 이슈
  apps/web/features/auction/bids/model/useBidSubmit.ts
  apps/web/features/auction/detail/api/useBidHistoryRealtime.ts
Labels: hotfix

#315 [✨ feat] 포인트 기능 개발
  apps/web/app/(header)/mypage/point/page.tsx
  apps/web/app/api/cron/resolve-auction/route.ts
  apps/web/app/api/mypage/point/route.ts
  apps/web/app/api/profile/route.ts
  apps/web/entities/point/model/types.ts
  apps/web/entities/profiles/model/types.ts
  apps/web/features/mypage/ui/MypageProfileCard.tsx
  apps/web/features/point/api/createPointByReason.ts
  apps/web/features/point/api/getPointList.ts
  apps/web/features/point/api/getUserPoint.ts
  apps/web/features/point/lib/utils.ts
  apps/web/features/point/model/useGetPointList.ts
  apps/web/features/point/model/useUserProfile.ts
  apps/web/features/point/types/index.ts
  apps/web/features/point/ui/PointItem.tsx
  apps/web/features/point/ui/PointList.tsx
  apps/web/features/point/ui/PointPageContent.tsx
  apps/web/shared/lib/auth.ts
  apps/web/shared/lib/formatDate.ts
Labels: design, feat

#324 [🔧 fix] 이슈 테스트 피드백 반영
  apps/web/app/(plane)/splash/loading/page.tsx
  apps/web/app/(plane)/splash/welcome/page.tsx
  apps/web/app/api/auction/listings/route.ts
  apps/web/features/auction/bids/ui/BidDialog.tsx
  apps/web/features/auction/detail/ui/AuctionDetailPage.tsx
  apps/web/features/auction/detail/ui/BottomBar.tsx
  apps/web/features/product/ui/ProductList.tsx
  packages/ui/src/components/Dialog/Dialog.tsx
  packages/ui/src/components/Icon/AvatarFallbakIcon.tsx
Labels: fix

#335 [♻️ refactor] 상품 상세페이지 성능개선 - 이미지 blur 적용
  apps/web/app/api/auction/[shortId]/route.ts
  apps/web/entities/product/model/types.ts
  apps/web/entities/productImage/model/types.ts
  apps/web/features/auction/detail/lib/generateBlurImg.ts
  apps/web/features/auction/detail/ui/ProductImageSlider.tsx
  apps/web/package.json
  pnpm-lock.yaml
Labels: refactor

#336 [♻️ refactor] 카테고리 이미지 png->webP로 변경하여 성능개선
  apps/web/features/category/types/index.ts
  apps/web/features/category/ui/GridCategory.tsx
  apps/web/features/category/ui/InlineCategory.tsx
  apps/web/public/category/cate-accessories.png
  apps/web/public/category/cate-accessories.webp
  apps/web/public/category/cate-all.png
  apps/web/public/category/cate-all.webp
  apps/web/public/category/cate-appliances.png
  apps/web/public/category/cate-appliances.webp
  apps/web/public/category/cate-beauty.png
  apps/web/public/category/cate-beauty.webp
  apps/web/public/category/cate-book.png
  apps/web/public/category/cate-book.webp
  apps/web/public/category/cate-clothing.png
  apps/web/public/category/cate-clothing.webp
  apps/web/public/category/cate-digital.png
  apps/web/public/category/cate-digital.webp
  apps/web/public/category/cate-hobby.png
  apps/web/public/category/cate-hobby.webp
  apps/web/public/category/cate-interior.png
  apps/web/public/category/cate-interior.webp
  apps/web/public/category/cate-kitchen.png
  apps/web/public/category/cate-kitchen.webp
  apps/web/public/category/cate-pet.png
  apps/web/public/category/cate-pet.webp
  apps/web/public/category/cate-plants.png
  apps/web/public/category/cate-plants.webp
  apps/web/public/category/cate-processed-food.png
  apps/web/public/category/cate-processed-food.webp
  apps/web/public/category/cate-sports.png
  apps/web/public/category/cate-sports.webp
  apps/web/public/category/cate-ticket.png
  apps/web/public/category/cate-ticket.webp
Labels: refactor
