Repository KFE-E2E-SAJO/BIDER, pull requests merged in 2025-08, with the labels that each got.

#322 [🐞 hotfix] 출품 시 공백이 입력된 상태로 넘어가지 않도록 처리
  apps/web/features/product/model/useCreateProduct.ts
Labels: hotfix

#345 [🐞 hotfix] 배포 시점 상세 페이지 진입 시 리액트 에러 발생
  apps/web/shared/lib/ImageUploadPreview.tsx
Labels: hotfix

#368 [♻️ refactor] 입찰 내역 성능 개선
  apps/web/app/(header)/auction/bids/page.tsx
  apps/web/app/(header)/auction/listings/page.tsx
  apps/web/app/api/auction/bids/route.ts
  apps/web/app/api/auction/listings/route.ts
  apps/web/features/auction/bids/index.tsx
  apps/web/features/auction/bids/model/getBidList.ts
  apps/web/features/auction/bids/types/index.ts
  apps/web/features/auction/bids/ui/AuctionBids.tsx
  apps/web/features/auction/bids/ui/AuctionBidsTabs.tsx
  apps/web/features/auction/bids/ui/BidList.tsx
  apps/web/features/auction/listings/index.tsx
  apps/web/features/auction/listings/model/getListingList.ts
  apps/web/features/auction/listings/types/index.ts
  apps/web/features/auction/listings/ui/AuctionListings.tsx
  apps/web/features/auction/listings/ui/AuctionListingsTabs.tsx
  apps/web/features/auction/listings/ui/ListingList.tsx
  apps/web/features/product/ui/Skeleton.tsx
  packages/ui/src/components/Tabs/Tabs.tsx
Labels: refactor

#380 [🐞 hotfix] 회원가입 이메일 인증 pwa 경로
  apps/web/app/(plane)/find-id/page.tsx
  apps/web/app/(plane)/signup/page.tsx
  apps/web/app/auth/callback/page.tsx
  apps/web/features/find-id/lib/findAccountConfig.tsx
  apps/web/features/find-id/model/useFindId.ts
  apps/web/features/signup/SignUpForm.tsx
  apps/web/features/signup/model/useSignupForm.ts
  apps/web/features/signup/ui/EmailField.tsx
  apps/web/features/signup/ui/EmailVerifiedField.tsx
  apps/web/shared/lib/auth.ts
  apps/web/shared/lib/middleware/redirect.ts
Labels: hotfix

#384 [✨ feat] 홈화면 지도/목록 스와이핑
  apps/web/entities/auction/model/types.ts
  apps/web/entities/product/model/types.ts
  apps/web/features/auction/list/actions/getAuctionMakersAction.ts
  apps/web/features/auction/list/lib/utils.ts
  apps/web/features/auction/list/types/index.ts
  apps/web/features/auction/list/ui/AuctionList.tsx
  apps/web/features/home/types/index.ts
  apps/web/features/home/ui/HomeClientPage.tsx
  apps/web/features/location/ui/GoogleMapPinBottomCard.tsx
  apps/web/features/location/ui/GoogleMapView.tsx
  apps/web/features/location/ui/MapMarkers.tsx
  apps/web/features/location/ui/MarkerItem.tsx
  apps/web/shared/lib/ImageUploadPreview.tsx
  apps/web/styles/global.css
  apps/web/widgets/nav/Nav.tsx
Labels: feat

#386 [✨ feat] 채팅 구현
  apps/web/app/(base)/chat/page.tsx
  apps/web/app/(plane)/chat/[shortId]/page.tsx
  apps/web/app/api/chat/checkIsChatEnd/[shortId]/route.ts
  apps/web/app/api/chat/create/route.ts
  apps/web/app/api/chat/getChatRoomLink/route.ts
  apps/web/app/api/chat/route.ts
  apps/web/app/api/cron/resolve-auction/route.ts
  apps/web/app/api/system-message/route.ts
  apps/web/entities/chatRoom/model/types.ts
  apps/web/entities/message/model/types.ts
  apps/web/entities/systemMessage/model/types.ts
  apps/web/features/auction/detail/types/index.ts
  apps/web/features/auction/detail/ui/AuctionDetailClient.tsx
  apps/web/features/auction/detail/ui/BottomBar.tsx
  apps/web/features/chat/list/api/fetchIsChatEnd.ts
  apps/web/features/chat/list/api/getChatList.ts
  apps/web/features/chat/list/api/inactiveChat.ts
  apps/web/features/chat/list/api/useMessageRealtimeForList.ts
  apps/web/features/chat/list/lib/getTimeAgo.ts
  apps/web/features/chat/list/model/useChatList.ts
  apps/web/features/chat/list/model/useIsChatEnd.ts
  apps/web/features/chat/list/types/index.ts
  apps/web/features/chat/list/ui/ChatItem.tsx
  apps/web/features/chat/list/ui/ChatList.tsx
  apps/web/features/chat/list/ui/ChatListPageContent.tsx
  apps/web/features/chat/nav/api/useUnreadMessagesCount.ts
  apps/web/features/chat/room/api/createChatRoom.ts
  apps/web/features/chat/room/api/createSystemMessage.ts
  apps/web/features/chat/room/api/getAuctionInfo.ts
  apps/web/features/chat/room/api/getChatRoomIdIfExist.ts
  apps/web/features/chat/room/api/getMessages.ts
  apps/web/features/chat/room/api/getProductInfoForSystemMessage.ts
  apps/web/features/chat/room/api/getSystemMessage.ts
  apps/web/features/chat/room/api/getYourNickName.ts
  apps/web/features/chat/room/api/sendMessage.ts
  apps/web/features/chat/room/api/setMessageRead.ts
  apps/web/features/chat/room/api/useMessageRealtime.ts
  apps/web/features/chat/room/lib/utils.ts
  apps/web/features/chat/room/model/getChatRoomLink.ts
  apps/web/features/chat/room/model/useAuctionInfo.ts
  apps/web/features/chat/room/model/useCombiedMessages.ts
  apps/web/features/chat/room/types/index.ts
  apps/web/features/chat/room/ui/AuctionInfo.tsx
  apps/web/features/chat/room/ui/BidWinMessage.tsx
  apps/web/features/chat/room/ui/ChatInputBar.tsx
  apps/web/features/chat/room/ui/ChatPageContent.tsx
  apps/web/features/chat/room/ui/DateDivider.tsx
  apps/web/features/chat/room/ui/MessageList.tsx
  apps/web/features/chat/room/ui/MyMessage.tsx
  apps/web/features/chat/room/ui/YourMessage.tsx
  apps/web/features/product/ui/ProductActionBtn.tsx
  apps/web/shared/ui/badge/StatusBadge.tsx
  apps/web/shared/ui/listItem/SwipeableItem.tsx
  apps/web/widgets/header/Header.tsx
  apps/web/widgets/header/ui/HeaderItem.tsx
  apps/web/widgets/nav/Nav.tsx
  packages/ui/src/components/Input/Input.tsx
  packages/ui/src/components/Textarea/Textarea.tsx
  packages/ui/src/global.css
Labels: design, feat

#388 [🐞 hotfix] 제안하기 코드 수정
  apps/web/app/(header)/mypage/proposal/received/[proposalId]/page.tsx
  apps/web/app/api/auction/[shortId]/proposal/route.ts
  apps/web/app/api/auction/[shortId]/proposal/target-product/route.ts
  apps/web/app/api/proposal/received-proposal/proposal-detail/route.ts
  apps/web/app/api/proposal/received-proposal/route.ts
  apps/web/app/api/proposal/sent-proposal/route.ts
  apps/web/features/proposal/list/model/getProposalDetail.ts
  apps/web/features/proposal/list/model/getReceivedProposal.ts
  apps/web/features/proposal/list/model/getSentProposal.ts
  apps/web/features/proposal/list/ui/ProposalDetail.tsx
  apps/web/features/proposal/list/ui/ReceivedContents.tsx
  apps/web/features/proposal/list/ui/ReceivedProposal.tsx
  apps/web/features/proposal/list/ui/SentContents.tsx
  apps/web/features/proposal/list/ui/SentProposal.tsx
  apps/web/features/proposal/make/model/getProposalPrice.ts
  apps/web/features/proposal/make/model/getTargetProduct.ts
  apps/web/features/proposal/make/ui/MakePrice.tsx
  apps/web/features/proposal/make/ui/MakeProposal.tsx
  apps/web/features/proposal/make/ui/TargetProduct.tsx
Labels: hotfix

#402 [✨ design] 홈 상품 리스트 하단 여백 수정
  apps/web/features/home/ui/HomeClientPage.tsx
Labels: design

#413 [🐞 hotfix] 제안하기 userId params 수정
  apps/web/app/api/auction/[shortId]/proposal/target-product/route.ts
Labels: hotfix

#417 [🐞 hotfix] deploy 배포 이슈 수정
  apps/web/app/api/auction/[shortId]/proposal/target-product/route.ts
Labels: hotfix

#406 [✨ feat] 푸시알림 기능 구현
  apps/web/app/(header)/alarm/page.tsx
  apps/web/app/(header)/alarm/setting/page.tsx
  apps/web/app/(plane)/alarm/page.tsx
  apps/web/app/actions.ts
  apps/web/app/api/alarm/auction/bid/route.ts
  apps/web/app/api/alarm/auction/nobid/route.ts
  apps/web/app/api/alarm/auction/startBid/route.ts
  apps/web/app/api/alarm/auction/winningBid/route.ts
  apps/web/app/api/alarm/chat/route.ts
  apps/web/app/api/alarm/nav/useAlarmCount.ts
  apps/web/app/api/alarm/point/route.ts
  apps/web/app/api/alarm/proposal/proposal-accepted/route.ts
  apps/web/app/api/alarm/proposal/proposal-pending/route.ts
  apps/web/app/api/auction/[shortId]/route.ts
  apps/web/app/api/auth/login/route.ts
  apps/web/app/api/cron/create-auction/route.ts
  apps/web/app/api/cron/resolve-auction/route.ts
  apps/web/app/pushTest/page.tsx
  apps/web/features/alarm/setting/lib/getPushAlarmMessage.ts
  apps/web/features/alarm/setting/model/useCreatePushToken.ts
  apps/web/features/alarm/setting/useAlarmSetting.ts
  apps/web/features/alarm/type/type.ts
  apps/web/features/alarm/useAlarmList.ts
  apps/web/features/chat/room/api/sendMessage.ts
  apps/web/features/chat/room/ui/ChatInputBar.tsx
  apps/web/features/login/model/useLogin.ts
  apps/web/features/proposal/list/ui/ProposalDetail.tsx
  apps/web/features/proposal/make/ui/MakePrice.tsx
  apps/web/public/sw.js
  apps/web/widgets/header/Header.tsx
  apps/web/widgets/header/ui/HeaderItem.tsx
  pnpm-lock.yaml
Labels: feat

#423 [🐞 hotfix] 회원가입 시 포인트 알림 전송
  apps/web/app/actions.ts
  apps/web/app/api/alarm/point/route.ts
  apps/web/app/api/auth/login/route.ts
  apps/web/features/login/model/useLogin.ts
  apps/web/features/point/types/index.ts
  apps/web/features/signup/model/useSignupForm.ts
Labels: hotfix

#429 [🔧 fix] 출품/입찰 금액 overflow 에러 처리
  apps/web/app/(header)/product/edit/[shortId]/page.tsx
  apps/web/app/(header)/product/registration/page.tsx
  apps/web/features/auction/bids/model/useBidSubmit.ts
  apps/web/features/product/lib/utils.ts
  apps/web/features/product/model/useProductEdit.ts
  apps/web/features/product/model/useProductForEdit.ts
  apps/web/features/product/ui/ProductEditForm.tsx
  apps/web/features/product/ui/ProductForm.tsx
Labels: fix, refactor

#432 [🐞 hotfix] 상품 상세페이지 카테고리 클릭 시 연결되는 링크 수정
  apps/web/features/auction/detail/ui/AuctionDetail.tsx
Labels: hotfix

#441 [🐞 hotfix] 제안하기 api 에러 수정
  apps/web/app/api/auction/[shortId]/proposal/target-product/route.ts
  apps/web/features/proposal/make/model/getTargetProduct.ts
  apps/web/features/proposal/make/ui/MakePrice.tsx
Labels: hotfix
